sudo: required
services:
  - docker

before_install:
  - docker build -t ranjanra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ranjanra/react-test npm test -- --coverage
after_success:
  - docker build -t ranjanra/multi-client ./client
  - docker build -t ranjanra/multi-nginx ./nginx
  - docker build -t ranjanra/multi-server ./server
  - docker build -t ranjanra/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # take those images and put them to docker hub
  - docker push ranjanra/multi-client
  - docker push ranjanra/multi-nginx
  - docker push ranjanra/multi-server
  - docker push ranjanra/multi-worker
  # Touching
